import { BlockData, BlockType, ItemData } from '../types/game';

export const BLOCKS: Record<BlockType, BlockData> = {
  [BlockType.AIR]: {
    id: BlockType.AIR,
    name: 'Air',
    hardness: 0,
    bestTool: 'none',
    minTier: 0,
    transparent: true,
    solid: false,
  },
  [BlockType.GRASS]: {
    id: BlockType.GRASS,
    name: 'Grass Block',
    hardness: 0.6,
    bestTool: 'shovel',
    minTier: 0,
    solid: true,
    dropItem: 'dirt',
  },
  [BlockType.DIRT]: {
    id: BlockType.DIRT,
    name: 'Dirt',
    hardness: 0.5,
    bestTool: 'shovel',
    minTier: 0,
    solid: true,
    dropItem: 'dirt',
  },
  [BlockType.STONE]: {
    id: BlockType.STONE,
    name: 'Stone',
    hardness: 1.5,
    bestTool: 'pickaxe',
    minTier: 1,
    solid: true,
    dropItem: 'cobblestone',
  },
  [BlockType.COBBLESTONE]: {
    id: BlockType.COBBLESTONE,
    name: 'Cobblestone',
    hardness: 2.0,
    bestTool: 'pickaxe',
    minTier: 1,
    solid: true,
    dropItem: 'cobblestone',
  },
  [BlockType.BEDROCK]: {
    id: BlockType.BEDROCK,
    name: 'Bedrock',
    hardness: 9999,
    bestTool: 'none',
    minTier: 4,
    solid: true,
  },
  [BlockType.OAK_LOG]: {
    id: BlockType.OAK_LOG,
    name: 'Oak Log',
    hardness: 2.0,
    bestTool: 'axe',
    minTier: 0,
    solid: true,
    dropItem: 'oak_log',
  },
  [BlockType.OAK_LEAVES]: {
    id: BlockType.OAK_LEAVES,
    name: 'Oak Leaves',
    hardness: 0.2,
    bestTool: 'none',
    minTier: 0,
    transparent: true,
    solid: true,
    dropItem: 'apple',
    dropCount: 1,
  },
  [BlockType.OAK_PLANKS]: {
    id: BlockType.OAK_PLANKS,
    name: 'Oak Planks',
    hardness: 2.0,
    bestTool: 'axe',
    minTier: 0,
    solid: true,
    dropItem: 'oak_planks',
  },
  [BlockType.SAND]: {
    id: BlockType.SAND,
    name: 'Sand',
    hardness: 0.5,
    bestTool: 'shovel',
    minTier: 0,
    solid: true,
    dropItem: 'sand',
  },
  [BlockType.CACTUS]: {
    id: BlockType.CACTUS,
    name: 'Cactus',
    hardness: 0.4,
    bestTool: 'none',
    minTier: 0,
    solid: true,
    dropItem: 'cactus',
  },
  [BlockType.SNOW]: {
    id: BlockType.SNOW,
    name: 'Snow Block',
    hardness: 0.2,
    bestTool: 'shovel',
    minTier: 0,
    solid: true,
    dropItem: 'snowball',
  },
  [BlockType.WATER]: {
    id: BlockType.WATER,
    name: 'Water',
    hardness: 100,
    bestTool: 'none',
    minTier: 0,
    transparent: true,
    solid: false,
  },
  [BlockType.GLASS]: {
    id: BlockType.GLASS,
    name: 'Glass',
    hardness: 0.3,
    bestTool: 'none',
    minTier: 0,
    transparent: true,
    solid: true,
  },
  [BlockType.COAL_ORE]: {
    id: BlockType.COAL_ORE,
    name: 'Coal Ore',
    hardness: 3.0,
    bestTool: 'pickaxe',
    minTier: 1,
    solid: true,
    dropItem: 'coal',
  },
  [BlockType.IRON_ORE]: {
    id: BlockType.IRON_ORE,
    name: 'Iron Ore',
    hardness: 3.0,
    bestTool: 'pickaxe',
    minTier: 2,
    solid: true,
    dropItem: 'raw_iron',
  },
  [BlockType.GOLD_ORE]: {
    id: BlockType.GOLD_ORE,
    name: 'Gold Ore',
    hardness: 3.0,
    bestTool: 'pickaxe',
    minTier: 3,
    solid: true,
    dropItem: 'raw_gold',
  },
  [BlockType.DIAMOND_ORE]: {
    id: BlockType.DIAMOND_ORE,
    name: 'Diamond Ore',
    hardness: 3.0,
    bestTool: 'pickaxe',
    minTier: 3,
    solid: true,
    dropItem: 'diamond',
  },
  [BlockType.BRICK]: {
    id: BlockType.BRICK,
    name: 'Bricks',
    hardness: 2.0,
    bestTool: 'pickaxe',
    minTier: 1,
    solid: true,
    dropItem: 'brick',
  },
  [BlockType.TORCH]: {
    id: BlockType.TORCH,
    name: 'Torch',
    hardness: 0,
    bestTool: 'none',
    minTier: 0,
    transparent: true,
    solid: false,
    lightLevel: 14,
    dropItem: 'torch',
  },
  [BlockType.CRAFTING_TABLE]: {
    id: BlockType.CRAFTING_TABLE,
    name: 'Crafting Table',
    hardness: 2.5,
    bestTool: 'axe',
    minTier: 0,
    solid: true,
    dropItem: 'crafting_table',
  },
  [BlockType.FURNACE]: {
    id: BlockType.FURNACE,
    name: 'Furnace',
    hardness: 3.5,
    bestTool: 'pickaxe',
    minTier: 1,
    solid: true,
    dropItem: 'furnace',
  },
  [BlockType.CHEST]: {
    id: BlockType.CHEST,
    name: 'Chest',
    hardness: 2.5,
    bestTool: 'axe',
    minTier: 0,
    solid: true,
    dropItem: 'chest',
  },
  [BlockType.TNT]: {
    id: BlockType.TNT,
    name: 'TNT',
    hardness: 0,
    bestTool: 'none',
    minTier: 0,
    solid: true,
    dropItem: 'tnt',
  },
  [BlockType.TALL_GRASS]: {
    id: BlockType.TALL_GRASS,
    name: 'Grass',
    hardness: 0,
    bestTool: 'none',
    minTier: 0,
    transparent: true,
    solid: false,
  },
  [BlockType.FLOWER_RED]: {
    id: BlockType.FLOWER_RED,
    name: 'Poppy',
    hardness: 0,
    bestTool: 'none',
    minTier: 0,
    transparent: true,
    solid: false,
    dropItem: 'flower_red',
  },
  [BlockType.FLOWER_YELLOW]: {
    id: BlockType.FLOWER_YELLOW,
    name: 'Dandelion',
    hardness: 0,
    bestTool: 'none',
    minTier: 0,
    transparent: true,
    solid: false,
    dropItem: 'flower_yellow',
  },
};

export const ITEMS: Record<string, ItemData> = {
  // Blocks as items
  grass_block: { id: 'grass_block', name: 'Grass Block', stackable: true, maxStack: 64, blockId: BlockType.GRASS, iconColor: '#5b8731' },
  dirt: { id: 'dirt', name: 'Dirt', stackable: true, maxStack: 64, blockId: BlockType.DIRT, iconColor: '#866043' },
  stone: { id: 'stone', name: 'Stone', stackable: true, maxStack: 64, blockId: BlockType.STONE, iconColor: '#757575' },
  cobblestone: { id: 'cobblestone', name: 'Cobblestone', stackable: true, maxStack: 64, blockId: BlockType.COBBLESTONE, iconColor: '#616161' },
  oak_log: { id: 'oak_log', name: 'Oak Log', stackable: true, maxStack: 64, blockId: BlockType.OAK_LOG, iconColor: '#674d32' },
  oak_leaves: { id: 'oak_leaves', name: 'Oak Leaves', stackable: true, maxStack: 64, blockId: BlockType.OAK_LEAVES, iconColor: '#396924' },
  oak_planks: { id: 'oak_planks', name: 'Oak Planks', stackable: true, maxStack: 64, blockId: BlockType.OAK_PLANKS, iconColor: '#a17849' },
  sand: { id: 'sand', name: 'Sand', stackable: true, maxStack: 64, blockId: BlockType.SAND, iconColor: '#dbcc90' },
  cactus: { id: 'cactus', name: 'Cactus', stackable: true, maxStack: 64, blockId: BlockType.CACTUS, iconColor: '#587a38' },
  snow: { id: 'snow', name: 'Snow', stackable: true, maxStack: 64, blockId: BlockType.SNOW, iconColor: '#f0f4f8' },
  glass: { id: 'glass', name: 'Glass', stackable: true, maxStack: 64, blockId: BlockType.GLASS, iconColor: '#a8d8ea' },
  brick: { id: 'brick', name: 'Bricks', stackable: true, maxStack: 64, blockId: BlockType.BRICK, iconColor: '#9e4638' },
  torch: { id: 'torch', name: 'Torch', stackable: true, maxStack: 64, blockId: BlockType.TORCH, iconColor: '#ffaa00' },
  crafting_table: { id: 'crafting_table', name: 'Crafting Table', stackable: true, maxStack: 64, blockId: BlockType.CRAFTING_TABLE, iconColor: '#b88b58' },
  furnace: { id: 'furnace', name: 'Furnace', stackable: true, maxStack: 64, blockId: BlockType.FURNACE, iconColor: '#5e5e5e' },
  chest: { id: 'chest', name: 'Chest', stackable: true, maxStack: 64, blockId: BlockType.CHEST, iconColor: '#996633' },
  tnt: { id: 'tnt', name: 'TNT', stackable: true, maxStack: 64, blockId: BlockType.TNT, iconColor: '#db3b3b' },
  flower_red: { id: 'flower_red', name: 'Poppy', stackable: true, maxStack: 64, blockId: BlockType.FLOWER_RED, iconColor: '#e03030' },
  flower_yellow: { id: 'flower_yellow', name: 'Dandelion', stackable: true, maxStack: 64, blockId: BlockType.FLOWER_YELLOW, iconColor: '#f0d030' },

  // Crafting components & ores
  stick: { id: 'stick', name: 'Stick', stackable: true, maxStack: 64, iconColor: '#8a6035' },
  coal: { id: 'coal', name: 'Coal', stackable: true, maxStack: 64, iconColor: '#262626' },
  raw_iron: { id: 'raw_iron', name: 'Raw Iron', stackable: true, maxStack: 64, iconColor: '#c49b82' },
  iron_ingot: { id: 'iron_ingot', name: 'Iron Ingot', stackable: true, maxStack: 64, iconColor: '#d6d6d6' },
  raw_gold: { id: 'raw_gold', name: 'Raw Gold', stackable: true, maxStack: 64, iconColor: '#f2cd49' },
  gold_ingot: { id: 'gold_ingot', name: 'Gold Ingot', stackable: true, maxStack: 64, iconColor: '#ffdf00' },
  diamond: { id: 'diamond', name: 'Diamond', stackable: true, maxStack: 64, iconColor: '#4deeea' },
  flint: { id: 'flint', name: 'Flint', stackable: true, maxStack: 64, iconColor: '#3c3d42' },
  flint_and_steel: { id: 'flint_and_steel', name: 'Flint and Steel', stackable: false, maxStack: 1, iconColor: '#e67e22' },
  gunpowder: { id: 'gunpowder', name: 'Gunpowder', stackable: true, maxStack: 64, iconColor: '#525252' },

  // Food
  apple: { id: 'apple', name: 'Apple', stackable: true, maxStack: 64, foodValue: 4, iconColor: '#e02828' },
  porkchop: { id: 'porkchop', name: 'Raw Porkchop', stackable: true, maxStack: 64, foodValue: 3, iconColor: '#e8998d' },
  cooked_porkchop: { id: 'cooked_porkchop', name: 'Cooked Porkchop', stackable: true, maxStack: 64, foodValue: 8, iconColor: '#a15637' },

  // Tools - Wooden
  wooden_pickaxe: { id: 'wooden_pickaxe', name: 'Wooden Pickaxe', stackable: false, maxStack: 1, toolType: 'pickaxe', toolTier: 1, attackDamage: 2, iconColor: '#8f683a' },
  wooden_axe: { id: 'wooden_axe', name: 'Wooden Axe', stackable: false, maxStack: 1, toolType: 'axe', toolTier: 1, attackDamage: 3, iconColor: '#8f683a' },
  wooden_shovel: { id: 'wooden_shovel', name: 'Wooden Shovel', stackable: false, maxStack: 1, toolType: 'shovel', toolTier: 1, attackDamage: 1, iconColor: '#8f683a' },
  wooden_sword: { id: 'wooden_sword', name: 'Wooden Sword', stackable: false, maxStack: 1, toolType: 'sword', toolTier: 1, attackDamage: 4, iconColor: '#8f683a' },

  // Tools - Stone
  stone_pickaxe: { id: 'stone_pickaxe', name: 'Stone Pickaxe', stackable: false, maxStack: 1, toolType: 'pickaxe', toolTier: 2, attackDamage: 3, iconColor: '#888888' },
  stone_axe: { id: 'stone_axe', name: 'Stone Axe', stackable: false, maxStack: 1, toolType: 'axe', toolTier: 2, attackDamage: 4, iconColor: '#888888' },
  stone_shovel: { id: 'stone_shovel', name: 'Stone Shovel', stackable: false, maxStack: 1, toolType: 'shovel', toolTier: 2, attackDamage: 2, iconColor: '#888888' },
  stone_sword: { id: 'stone_sword', name: 'Stone Sword', stackable: false, maxStack: 1, toolType: 'sword', toolTier: 2, attackDamage: 5, iconColor: '#888888' },

  // Tools - Iron
  iron_pickaxe: { id: 'iron_pickaxe', name: 'Iron Pickaxe', stackable: false, maxStack: 1, toolType: 'pickaxe', toolTier: 3, attackDamage: 4, iconColor: '#e0e0e0' },
  iron_axe: { id: 'iron_axe', name: 'Iron Axe', stackable: false, maxStack: 1, toolType: 'axe', toolTier: 3, attackDamage: 5, iconColor: '#e0e0e0' },
  iron_shovel: { id: 'iron_shovel', name: 'Iron Shovel', stackable: false, maxStack: 1, toolType: 'shovel', toolTier: 3, attackDamage: 3, iconColor: '#e0e0e0' },
  iron_sword: { id: 'iron_sword', name: 'Iron Sword', stackable: false, maxStack: 1, toolType: 'sword', toolTier: 3, attackDamage: 6, iconColor: '#e0e0e0' },

  // Tools - Diamond
  diamond_pickaxe: { id: 'diamond_pickaxe', name: 'Diamond Pickaxe', stackable: false, maxStack: 1, toolType: 'pickaxe', toolTier: 4, attackDamage: 5, iconColor: '#33f0e0' },
  diamond_axe: { id: 'diamond_axe', name: 'Diamond Axe', stackable: false, maxStack: 1, toolType: 'axe', toolTier: 4, attackDamage: 6, iconColor: '#33f0e0' },
  diamond_shovel: { id: 'diamond_shovel', name: 'Diamond Shovel', stackable: false, maxStack: 1, toolType: 'shovel', toolTier: 4, attackDamage: 4, iconColor: '#33f0e0' },
  diamond_sword: { id: 'diamond_sword', name: 'Diamond Sword', stackable: false, maxStack: 1, toolType: 'sword', toolTier: 4, attackDamage: 7, iconColor: '#33f0e0' },
};
